### ISSUE TITLE
Allow multiple projects to be used simultaneously

### ISSUE THREAD

**Issue by malbiez** [vikepic/standup-boy#6]
My company forces me to do standups in multiple projects via Mattermost (...) It would be awesome if there was a way to provide an optional --project parameter which essentials picks a specific Mattermost URL, Username and Channel from the config.json file.

**Comment by vikepic** [comment]
So, something like this, right?

```
{
  "projects" :
   {
      "project-turnip":
        {
          "username" : "vikepic",
	  "channel" : "daily-standup-turnip",
	  "url" : "https://your-slack-url"
        },
      "project-avocado":
        {
          "username" : "vikepic",
	  "channel" : "daily-standup-avocado",
	  "url" : "https://your-slack-url"
        }
    } 
}
```

Then you just `standup-boy --project project-turnip`. Right?

**Comment by vikepic** [comment]
Or we could use https://www.npmjs.com/package/inquirer#list---type-list

**Comment by malbiez** [comment]
`standup-boy --project project-turnip` is a nice idea I think :)

**Comment by vikepic** [comment]
I ended up supporting both alternatives. If no flag is provided and there are multiple projects to choose from, the program prompts for clarification :)
